name: 'Get release version'
description: 'Setup RELEASE_VERSION environment variable from GITHUB_REF'

runs:
  using: "composite"
  steps:
    - name: Get release version
      id: version_number
      shell: bash
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
        echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_OUTPUT
        echo "RELEASE_VERSION_NO_v=${GITHUB_REF:11}" >> $GITHUB_ENV
        echo "RELEASE_VERSION_NO_v=${GITHUB_REF:11}" >> $GITHUB_OUTPUT
