name: Docker image

on:
  push:
    branches: master

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get release version
        run: echo "${GITHUB_REF:10}" >> $RELEASE_VERSION
      - name: Run unit tests
        run: ./unit-tests.sh
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: Run integration tests
        run: ./integration-tests.sh
      - name: Run HELM chart tests
        run: ./helm/tests.sh
      - name: Build master
        env:
          DOCKER_USERNAME: 'boky'
          DOCKER_PASSWORD: '${{ secrets.DOCKER_ACCESS_TOKEN }}'
          PLATFORMS: "linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le"
        run: ./build.sh -t boky/postfix --push

