name: Validate pull request

on:
  pull_request:
    branches: [ 'master' ]

jobs:
  "Unit Tests":
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/unit-tests
  "Integration Tests":
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/integration-tests
  "Helm chart Tests":
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/helm-chart-tests

  "Build Alpine":
    runs-on: ubuntu-latest
    needs:
      - "Unit Tests"
      - "Integration Tests"
      - "Helm chart Tests"
    steps:
      - uses: ./.github/actions/buildx-setup










      - name: Get release version
        id: version_number
        shell: bash
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
          echo "::set-output name=RELEASE_VERSION::${GITHUB_REF:10}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          #key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-







      - name: Fix issue with building Alpine # See https://gitlab.alpinelinux.org/alpine/aports/-/issues/12406
        run: |
          update-binfmts --enable

      - name: Build Alpine
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: |
            boky/postfix:latest
            boky/postfix:latest-alpine
          platforms: "linux/amd64"
          cache-from: type=local,src=/tmp/.buildx-cache/alpine

          build-args: |
            BASE_IMAGE=alpine:latest
