name: Docker tag image

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tag
        uses: actions/checkout@v2

      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: "gh-pages"


      - name: Get the build version number
        shell: bash
        run: |
          echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Build branch / tag
        env:
          DOCKER_USERNAME: 'boky'
          DOCKER_PASSWORD: '${{ secrets.DOCKER_ACCESS_TOKEN }}'
          PLATFORMS: "linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le"
        run: ./build.sh -t boky/postfix:$RELEASE_VERSION --push
      - name: Package helm chart
        uses: WyriHaximus/github-action-helm3@v2
        with:
          # Successfully packaged chart and saved it to: /Users/boky/development/projects/docker-postfix/mail-2.1.0.tgz
          exec: helm package --app-version $RELEASE_VERSION --version $RELEASE_VERSION --destination ./public helm/mail
      - name: Chart to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
